### ISSUE TITLE
flexCells prop passed down through ...rest

### ISSUE THREAD

**Issue by therealolivierl** [kodyl/react-flexr#14]
Same as https://github.com/kodyl/react-flexr/issues/11 but for the flexCells prop for the Grid element.

**Comment by danieljuhl** [comment]
Are you using the latest version `v2.1.1`? `flexCells` is not part of `...rest` for `Grid`.

**Comment by therealolivierl** [comment]
My bad, we were using flexCell instead of flexCells. Apologies.

**Comment by danieljuhl** [comment]
No problem 👍
