### ISSUE TITLE
babel-runtime is a dependency, not devDependency

### ISSUE THREAD

**Issue by pushplay** [kodyl/react-flexr#16]
`babel-runtime` is called out in `package.json` under `devDependencies`, but it's referenced by name in https://github.com/kodyl/react-flexr/blob/master/dist/index.js#L7 and is thus a run time dependency.  It should be in `package.json` under `dependencies` to be sure all run time dependencies install correctly.

**Comment by danieljuhl** [comment]
Indeed! I'll look at this ASAP
