### ISSUE TITLE
How to set direction?

### ISSUE THREAD

**Issue by vomchik** [kodyl/react-flexr#3]
How to set direction?

**Comment by chriskjaer** [comment]
https://github.com/kodyl/react-flexr#grid explaines how you can align sub items in the grid 
and https://github.com/kodyl/react-flexr#cell explaines how to align a single element inside the Grid container.

Is there any of those things that's not working for you?

**Comment by vomchik** [comment]
No. I talk about flex-direction: row|column.

**Comment by danieljuhl** [comment]
@vomchik is this still relevant? It should be possible to simply apply the style inline, eg `<Grid ... style={{ flexDirection: 'column' }}>...</Grid>`

**Comment by danieljuhl** [comment]
I'm closing this for now, as I don't see any reason to build any extra logic regarding flex-direction into `react-flexr`, as it is easy to control using `style` or `className`. If you have good reasons, to add logic in the module, please let me know.
