### ISSUE TITLE
Grid doesnt handle webkits

### ISSUE THREAD

**Issue by olivierGM** [kodyl/react-flexr#4]
I am having a problem where react-flexr doesn't work in safari on a tablet and "solved by flexbox" works on safari. It seems like webkits aren't specified for the Grid. (reference : https://github.com/kodyl/react-flexr/blob/master/lib/grid.component.js#L9)

**Comment by louiscloutierdakis** [comment]
There is a discussion about this issue here: facebook/react#2020

**Comment by louiscloutierdakis** [comment]
@olivierGM I think you could use something like https://github.com/postcss/autoprefixer, since react-flexr generates the css file in node_modules/react-flexr/styles.css

**Comment by danieljuhl** [comment]
That's right - you have to use autoprefixer. We've decided to leave postcss and autoprefixing to the developer.

**Comment by olivierGM** [comment]
I implemented autoprefixer and now its working, thanks !
