### ISSUE TITLE
Having a cell with a fixed size

### ISSUE THREAD

**Issue by olivierGM** [kodyl/react-flexr#7]
Would it be possible to have a cell with a fixed size (i.e 100px) or is there already a way of handling that? Currently only fractions are supported ,and my sidebar (who have a fixed width) needs to be contained in a custom div in the grid rather than in a cell.

Example:
```javascript
<Cell palm="100px" lap="200px" desk="300px" />
```

**Comment by danieljuhl** [comment]
I'll have a look at this shortly...

**Comment by olivierGM** [comment]
alright cool

**Comment by olivierGM** [comment]
Any update ?

**Comment by danieljuhl** [comment]
Sorry, I haven't had much spare time lately, but I'm actually looking at this now. I have a use case myself, so you can expect an update soon.

**Comment by danieljuhl** [comment]
It is already possible to set a fixed width for a `<Cell>`, simply provide the width as inline-style or using a class and have the size defined in your stylesheet.

And regarding breakpoint depend width, it can be handled in your stylesheet as well, and actually also as inline-style, using the findMatch helper, to detect the rendered breakpoint.

**Comment by danieljuhl** [comment]
I have now made the changes, but I will hold back the release for a few days, as I would like to go through the code, and see if everything is as performant as possible.

**Comment by danieljuhl** [comment]
Closed in 92e5e36218b18877a6167dd0fc836736c047401a, I'll make a release and publish a new version to npm early next week

**Comment by olivierGM** [comment]
thanks +1

**Comment by danieljuhl** [comment]
There is a beta, `2.1.0-beta`
