### ISSUE TITLE
use babel 6

### ISSUE THREAD

**Issue by danieljuhl** [kodyl/react-flexr#8]

**Comment by fdidron** [comment]
Hi, Would love babel 6 support as it seems I can't import flexr in my babel 6 project right now.
Would love to give a hand, is that as simple as changing the babel deps version on the package.json and run a make build ?

Thanks !

**Comment by danieljuhl** [comment]
What is the problem? I have a few babel 6 projects using `react-flexr` without problems.

**Comment by danieljuhl** [comment]
That said, I will upgrade to babel 6, probably next week, where I will also test `react-flexr` against `react@15.x`

**Comment by fdidron** [comment]
My bad seriously :/ Had to install babel-runtime in my project. Works like a charm, thanks for the great lib !
