### ISSUE TITLE
re-render on breakpoint change not happening

### ISSUE THREAD

**Issue by hervejegou** [kodyl/react-flexr#9]
I am using react-flexr on Meteor 1.3.1. The Grdi is working well, columns are OK and resize when I resize the window, and cell alignment also works. However, the breakpoints have no effect, grid is non responsive.

Here is the code:

```
import React from 'react';
...
import { Grid, Cell } from 'react-flexr';
import '/node_modules/react-flexr/styles.css';

class Profile extends React.Component {
....
render() {

    return (
      <div>
        <AppBar className={style.appbar} flat>
          <h1 className={style.title}>React Toolbox Example</h1>
        </AppBar>
        <section className={style.content}>
          <Grid>
            <Cell align='top' size={4/12} palm={6/12}>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Aenean commodo ligula eget dolor.Aenean massa.Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.Nulla consequat massa quis enim.
            </Cell>
            <Cell align='center' size={4/12} palm={6/12}>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            </Cell>
            <Cell align='bottom' size={4/12} palm={6/12}>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Aenean commodo ligula eget dolor.Aenean massa.Cum sociis natoque penatibus et magnis dis parturient montes
            </Cell>
          </Grid>
        </section>
      </div>    
    );
  }
}
export default Profile;
```

Do I need to import something else or set the breakpoints somewhere?? Thanks for any help.

**Comment by danieljuhl** [comment]
Have you tried reloading the page in another breakpoint, and see if that works?

**Comment by hervejegou** [comment]
Yes correct. It does work when you reload. So it is responsive but not in the traditional flexbox way (with breakpoints in css which work during resizing). Looking at the css:

```
element.style {
    width: 33.33%;
}
._2181U { //note: this is the cell align property - this stylesheet is different for each cell
    align-self: flex-start;
}
._11Q4tC { // this is the padding from the grid iself - this styleshee applies to all 3 cells
    padding: 0 11px;
// note: if width property can move here with media queries/breakpoints maybe it would work on resize??
}
```
It seems the width is fixed in the cell itself, then the cell style and grid style fix the rest ? Maybe in the future the breakpoints could be in the cell style itself (see note above) ?? in that way it would be responsive on resize? I may try this later on if I can figure it out...

This is working well already thanks. reloading on resize is not a big problem. issue is closed/solved. Thanks.

**Comment by hervejegou** [comment]
Quick related follow up:

I am trying to have a grid where cells are full width on palm and maybe 50% on lap and 33% on desk. I tried:
```<Cell align='top' size={4/12} lap={6/12} palm={1}>```
and also:
```<Cell align='top' size={4/12} lap={6/12} palm={12/12}>```

If I reload with a width smaller than 600px (palm breakpoint), the cell with is set to  ```width: 1px;```
How can I specify full width cell for palm breakpoint??

**Comment by danieljuhl** [comment]
@hervejegou We have a plan to include a standard grid (12 column) in the CSS, to enable CSS-based responsive changes. The reason we didn't do it initially, is that you can provide any fraction, and thus can build a 14-column grid if you want to.

The problem is that breakpoint changes does not trigger a re-render, if it did, it would work. We have also been working on an implementation, which handles that, but it requires a good use of `shouldComponentUpdate` to re-render as little as possible.

Full width cell, should be possible with `palm={12/12}` or `palm={1/1}`. If not, I will have to investigate. As `react-flexr` allows you to specify a fixed width in pixels, `palm={1}` will render `width: 1px`, it's by design - but it might be a bug, as it should only interpret as fixed width for sizes greater than `1`.

**Comment by hervejegou** [comment]
@danieljuhl regarding responsive on resize, I was thinking to use CSS media queries so there is no need to redraw or re render in React:

Right now when you set a cell to ```<Cell  align='top' size={3/12} palm={6/12}>```
the cel has the following calculated style attached by react-flexr:
```
element.style {
    width: 25%;
}
._2181U { // this is random style class attached to the cell by react-flexr??
    align-self: flex-start;
}
```
and if the window width is below 600px (palm), then the style is changed to:
```
element.style {
    width: 50%;
}
._2181U {
    align-self: flex-start;
}
```
But we need to reload to get this change when we resize the window width below 600px.

Maybe instead react-flexr could set the style to:
```
._2181U {
    width: 25%;
    align-self: flex-start;
}
@media (max-width: 600px) {
   ._2181U {
          width: 50%;
   }
   }
```
I tested it in React and it seems to work: the cell width will adjust as you resize the window. So this would not require a re render in React, it all works with CSS only??

I am not sure where to modify but this would be great.

**Comment by hervejegou** [comment]
@danieljuhl : I have tested both ```palm={12/12}''' or '''palm={1/1} ``` and it does not work. For now we use ```palm={99/100}``` to get a near full width... almost OK.

**Comment by danieljuhl** [comment]
@hervejegou Sorry for not getting back earlier.. the problem is that you are using a number fraction and not a string fraction.

`palm={1/1}` should have been `palm='1/1'` or `palm={'1/1'}`, otherwise I will just end up as the number `1` which is handled as a fixed size because of the type `Number`.
